# Generated by Django 4.1.5 on 2023-01-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('is_active', models.BooleanField(verbose_name='активность')),
                ('sort_index', models.PositiveIntegerField(verbose_name='индекс сортировки')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='', verbose_name='фотография')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='цена')),
                ('limited', models.BooleanField(default=False, verbose_name='ограниченный или нет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.category', verbose_name='категория')),
            ],
        ),
    ]
