# Generated by Django 4.1.5 on 2023-01-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_seller_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=100, verbose_name='тип доставки')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100, verbose_name='вид оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='SoldCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(verbose_name='статус оплаты')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.delivery', verbose_name='тип доставки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.item', verbose_name='товар')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.payment', verbose_name='вид оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('active', models.BooleanField(verbose_name='активность')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.cart', verbose_name='корзина')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.item', verbose_name='товар')),
            ],
        ),
    ]
