# Generated by Django 4.1.5 on 2023-01-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_cart_delivery_payment_soldcart_solditem_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
