# Generated by Django 4.1.5 on 2023-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_review_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
