# Generated by Django 4.1.5 on 2023-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0009_remove_cartitem_cart_remove_cartitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(max_length=150, null=True, verbose_name='подкатегория'),
        ),
    ]
