# Generated by Django 4.1.5 on 2023-01-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0011_remove_category_sub_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='sub_category',
        ),
    ]
