# Generated by Django 4.1.5 on 2023-01-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0012_rename_category_subcategory_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='category',
        ),
    ]
