# Generated by Django 4.1.5 on 2023-01-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0013_rename_sub_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_subcategory',
            field=models.BooleanField(default=False, verbose_name='наличие подкатегорий'),
        ),
    ]
