# Generated by Django 4.1.5 on 2023-01-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0017_rename_image_item_photo_image_item_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
