# Generated by Django 4.1.5 on 2023-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0018_rename_photo_item_image_remove_item_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фотография'),
        ),
    ]
