# Generated by Django 4.1.5 on 2023-01-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0019_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
