# Generated by Django 4.1.5 on 2023-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0020_category_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sold_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='сколько продаж'),
        ),
    ]
