# Generated by Django 4.1.5 on 2023-01-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0021_remove_category_sold_quantity_item_sold_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app_goods.category', verbose_name='категория'),
        ),
    ]
