# Generated by Django 4.1.5 on 2023-01-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0025_alter_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.delivery', verbose_name='доставка'),
        ),
    ]
