# Generated by Django 4.1.5 on 2023-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0026_item_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фотография 2'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фотография 3'),
        ),
    ]
