# Generated by Django 4.1.5 on 2023-02-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0027_item_image2_item_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='фотография'),
        ),
    ]
