# Generated by Django 4.1.5 on 2023-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0028_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
