# Generated by Django 4.1.5 on 2023-01-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0005_order_delete_soldcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
