# Generated by Django 4.1.5 on 2023-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_order_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitems',
            field=models.ManyToManyField(to='app_cart.cartitem'),
        ),
    ]
