# Generated by Django 4.1.5 on 2023-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0007_remove_order_items_order_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartitems',
            field=models.ManyToManyField(related_name='orders', to='app_cart.cartitem'),
        ),
    ]
