# Generated by Django 4.1.5 on 2023-01-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0008_alter_order_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_or_not', models.BooleanField(default=True, verbose_name='беслпатная доставка')),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_cart.order')),
            ],
        ),
    ]
