# Generated by Django 4.1.5 on 2023-01-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0009_orderdeliver'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDeliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.BooleanField(default=True, verbose_name='оплата онлайн')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_cart.order')),
            ],
        ),
    ]
