# Generated by Django 4.1.5 on 2023-01-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0012_alter_order_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер карты'),
        ),
    ]
