# Generated by Django 4.1.5 on 2023-01-30 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cart', '0013_alter_order_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplitedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('payed', models.BooleanField(verbose_name='оплачен')),
                ('error', models.CharField(max_length=155, verbose_name='текст ошибки')),
                ('cartitems', models.ManyToManyField(related_name='new_orders', to='app_cart.cartitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
