# Generated by Django 4.1.5 on 2023-01-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0026_item_delivery'),
        ('app_cart', '0014_complitedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complitedorder',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='complitedorder',
            name='items',
            field=models.ManyToManyField(related_name='items', to='app_goods.item'),
        ),
    ]
