# Generated by Django 4.1.5 on 2023-01-30 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cart', '0015_remove_complitedorder_cartitems_complitedorder_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complitedorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
