# Generated by Django 4.1.5 on 2023-01-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0016_alter_complitedorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complitedorder',
            name='order_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
