# Generated by Django 4.1.5 on 2023-01-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0019_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='complitedorder',
            name='delivery_method',
            field=models.BooleanField(default=False, verbose_name='экспресс-доставка'),
        ),
    ]
