# Generated by Django 4.1.5 on 2023-02-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0021_complitedorder_i_payed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'товар в корзине', 'verbose_name_plural': 'товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='complitedorder',
            options={'verbose_name': 'завершенный заказ', 'verbose_name_plural': 'завершенные заказы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'временный заказ', 'verbose_name_plural': 'временные заказы'},
        ),
        migrations.DeleteModel(
            name='SoldItem',
        ),
    ]
