# Generated by Django 4.1.5 on 2023-01-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0003_cart_delivery_payment_soldcart_solditem_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=155, verbose_name='отчество')),
                ('phone', models.IntegerField(verbose_name='телефон')),
                ('avatar', models.ImageField(upload_to='', verbose_name='аватар')),
                ('review', models.ManyToManyField(to='app_goods.review', verbose_name='оставленные отзывы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('viewed_items', models.ManyToManyField(to='app_goods.item', verbose_name='просмотренные товары')),
            ],
        ),
    ]
