# Generated by Django 4.1.5 on 2023-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_delete_seller'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='продавец')),
                ('items', models.ManyToManyField(to='app_goods.item', verbose_name='товары продавца')),
            ],
        ),
    ]
