# Generated by Django 4.1.5 on 2023-01-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
