# Generated by Django 4.1.5 on 2023-01-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_delete_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
    ]
