# Generated by Django 4.1.5 on 2023-01-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0009_remove_cartitem_cart_remove_cartitem_item_and_more'),
        ('app_users', '0005_alter_profile_viewed_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='viewed_items',
            field=models.ManyToManyField(default=None, null=True, to='app_goods.item', verbose_name='просмотренные товары'),
        ),
    ]
