# Generated by Django 4.1.5 on 2023-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0026_item_delivery'),
        ('app_users', '0009_alter_profile_viewed_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='viewed_items',
            field=models.ManyToManyField(blank=True, default=None, to='app_goods.item', verbose_name='просмотренные товары'),
        ),
    ]
