# Generated by Django 4.1.5 on 2023-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0016_alter_complitedorder_user'),
        ('app_users', '0010_alter_profile_viewed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(related_name='order', to='app_cart.complitedorder'),
        ),
    ]
