# Generated by Django 4.1.5 on 2023-01-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_profile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
    ]
