# Generated by Django 4.1.5 on 2023-02-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_remove_profile_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
    ]
